#!/bin/bash

if [ "$1" = "eth0" ]; then
	case "$2" in
		up)
			#sudo nmcli radio wifi off
			sudo ifconfig wlan0 down
			;;
		down)
			#sudo nmcli radio wifi on
			sudo ifconfig wlan0 up
			;;
	esac
fi

