#!/bin/bash

if [ "$1" = "eth0" ]; then
	case "$2" in
		up)
			sudo mount -o rw,remount /
			#nmcli radio wifi off
			rfkill block wlan
			;;
		down)
			sudo mount -o rw,remount /
			#nmcli radio wifi on
			rfkill unblock wlan
			;;
	esac
fi
sudo mount -o  ro,remount /
